# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
project_name: atlas-cli-plugin-example

version: 2

builds:
  - 
    id: "atlas-cli-plugin-example"
    main: ./main.go
    binary: ./bin/example

archives:
  - files:
      - ./manifest.yml