name: Copybara

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  copybara:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set env
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build Copybara
        run: | 
          # Clone the Copybara repository
          git clone --depth=1 https://github.com/google/copybara ${GITHUB_WORKSPACE}/copybara
          # Build the Docker image
          docker build -t google/copybara ${GITHUB_WORKSPACE}/copybara
          
      - name: Run Copybara
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WORKFLOW: docs-atlas-cli-fork
          TAG: ${{ env.TAG }}
        run: |
          pwd
          cd build/ci
          bash ./run-copybara.sh