name: Release

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - master
      - CLOUDP-261728

permissions:
  contents: write

jobs:
  release:
    if: "startsWith(github.ref, 'refs/tags/v')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up environment
        run: |
          VERSION=$(echo "${GITHUB_REF#refs/tags/v}")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
    
      - name: Add version to manifest file
        run: |
          envsubst < manifest.yml > manifest_temp.yml && mv manifest_temp.yml manifest.yml

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "latest"
          args: release --clean --skip=validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
