name: Release

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - master
      - CLOUDP-261728

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Environment Variables
        run: |
          echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
          echo "REPO_OWNER=${{ github.repository_owner }}" >> $GITHUB_ENV
          TAG_VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$TAG_VERSION" >> $GITHUB_ENV

      - name: Use Environment Variables in Inline Script
        run: |
          echo "Repository Name: $REPO_NAME"
          echo "Repository Owner: $REPO_OWNER"
          echo "Version: $VERSION"
        env:
          REPO_NAME: ${{ env.REPO_NAME }}
          REPO_OWNER: ${{ env.REPO_OWNER }}
          VERSION: ${{ env.VERSION }}

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: 'latest'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}