name: Release

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - master
      - CLOUDP-261728

permissions:
  contents: write

jobs:
  release:
    if: "startsWith(github.ref, 'refs/tags/v')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Update file
        run: |
          echo "Updating file" > updated-file.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add updated-file.txt
          git commit -m "Update file via GitHub Actions"
          git push origin ${{ github.ref }}

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser-pro
          version: "latest"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
